### ISSUE TITLE
/home/bot/.local/share/pycoq/pycoq.log needed?

### ISSUE THREAD

**Issue by brando90** [brando90/pycoq#2]
odd error with pycoq.log
```
Traceback (most recent call last):
  File "/home/bot/pycoq/tutorial/brandos_pycoq_tutorial.py", line 16, in <module>
    import pycoq.opam
  File "/home/bot/pycoq/pycoq/opam.py", line 13, in <module>
    import pycoq.trace
  File "/home/bot/pycoq/pycoq/trace.py", line 19, in <module>
    from pycoq.common import CoqContext, context_fname, dump_context
  File "/home/bot/pycoq/pycoq/common.py", line 10, in <module>
    import pycoq.log
  File "/home/bot/pycoq/pycoq/log.py", line 42, in <module>
    config_logging()
  File "/home/bot/pycoq/pycoq/log.py", line 19, in config_logging
    logging.basicConfig(
  File "/home/bot/miniconda3/envs/pycoq/lib/python3.9/logging/__init__.py", line 2003, in basicConfig
    h = FileHandler(filename, mode,
  File "/home/bot/miniconda3/envs/pycoq/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/bot/miniconda3/envs/pycoq/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: '/home/bot/.local/share/pycoq/pycoq.log'
```

**Comment by brando90** [comment]
solution, log to the log file and to stdout. Do not create logfile in your own script, since it needs to know about it when pycoq imports opam that import log.
```
# FORMATTER = '--> %(asctime)s - %(process)d - %(name)s - %(levelname)s - %(message)s ----'
# https://stackoverflow.com/questions/533048/how-to-log-source-file-name-and-line-number-in-python
FORMATTER = '--> [%(asctime)s] p%(process)s {%(pathname)s:%(lineno)d} %(levelname)s - %(message)s <--'

def logging_level(a: int):
    ''' returns logging level '''
    return {1: logging.CRITICAL,
            2: logging.ERROR,
            3: logging.WARNING,
            4: logging.INFO,
            5: logging.DEBUG}[a]

def config_logging():
    """Configures python's logging module to print to stdout and logging file."""
    logging.basicConfig(
        format=FORMATTER,
        level=logging_level(pycoq.config.get_log_level()),
        handlers=[
            logging.FileHandler(pycoq.config.get_log_filename()),
            logging.StreamHandler()
        ]
    )
```
